//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public int CategoryID { get; set; }
        public string Picture { get; set; }
        public string MovieTrailer { get; set; }
        public Nullable<bool> IsActiv { get; set; }
        public Nullable<int> Level { get; set; }
    
        public virtual Categorys Categorys { get; set; }
        public virtual Prices Prices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
